editAreaLoader.lang["ru"]={
new_document: "новый пустой документ",
search_button: "поиск и замена",
search_command: "искать далее / открыть поиск",
search: "поиск",
replace: "замена",
replace_command: "замена / открыть поиск",
find_next: "найти далее",
replace_all: "заменить всё",
reg_exp: "регулярное выражение",
match_case: "с учётом геристра",
not_found: "не найдено.",
occurrence_replaced: "заменено.",
search_field_empty: "Не введена строка поиска",
restart_search_at_begin: "End of area reached. Restart at begin.",
move_popup: "move search popup",
font_size: "--размер шрифта--",
go_to_line: "перейти на строку",
go_to_line_prompt: "перейти на строку:",
undo: "отменить",
redo: "повторить",
change_smooth_selection: "enable/disable some display features (smarter display but more CPU charge)",
highlight: "Вкл/выкл подсветку синтаксиса",
reset_highlight: "reset highlight (if desyncronized from text)",
help: "помощь",
save: "сохранить",
save_as: "сохранить как",
load: "Загрузить",
line_abbr: "Стр",
char_abbr: "Симв",
position: "Позиция",
total: "Всего",
close_popup: "закрыть вспл. окно",
shortcuts: "Ярлыки",
add_tab: "Добавить табуляции к тексту",
remove_tab: "удалить табуляции из текста",
about_notice: "Notice: syntax highlight function is only for small text",
toggle: "Включить редактор",
accesskey: "Accesskey",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Обработка...",
fullscreen: "во весь экран"
};
